const translations = {
  nl: {
    page_title: "Zaans Recht - Eerlijk juridisch advies",
    language_label: "Taal",
    close_notification: "Melding sluiten",
    nav_about: "Over ons",
    nav_services: "Diensten",
    nav_contact: "Contact",
    welcome: "Welkom bij Zaans Recht!",
    hero_intro: "Wij geven gratis juridisch advies en duidelijkheid over uw rechten",
    hero_explanation: "Zo zorgen we ervoor dat u uw juridische situatie eenvoudig en begrijpelijk kunt overzien.",
    hero_action: "Bij Zaans Recht staat uw recht centraal. Heeft u vragen of behoefte aan ondersteuning? Maak dan een afspraak!",
    make_appointment: "Maak een afspraak",
    about_title: "Over ons",
    about_description_1: "Bij Zaans Recht bieden wij gratis juridisch advies aan iedereen die vragen heeft over zijn of haar rechten. Ons doel is om mensen te helpen hun juridische situatie helder te krijgen en begrijpelijk advies te geven, zodat zij bewuste beslissingen kunnen nemen.",
    about_description_2: "Wij begrijpen dat juridische kwesties ingewikkeld kunnen zijn. Daarom staan wij klaar om u te begeleiden met advies over diverse rechtsgebieden. Naast gratis advies, bieden wij ook de mogelijkheid om juridische stukken voor u op te stellen, zoals bezwaarschriften en klachtenbrieven. Hieraan zijn kosten verbonden, die wij vooraf met u bespreken.",
    walk_in: "Elke donderdagmiddag om 16:00 uur kunt u zonder afspraak binnenlopen tijdens ons inloopspreekuur in Bibliotheek Zaandam (Westzijde 170 A, 1506 EK Zaandam).",
    services_title: "Diensten",
    corporate_law: "Ondernemingsrecht",
    corporate_law_description: "Juridische ondersteuning voor ondernemers, van contracten tot geschillen.",
    family_law: "Familierecht",
    family_law_description: "Begeleiding bij echtscheiding, alimentatie en omgangsregelingen.",
    employment_law: "Arbeidsrecht",
    employment_law_description: "Advies bij arbeidsconflicten, ontslagen en arbeidsovereenkomsten.",
    administrative_law: "Bestuursrecht",
    administrative_law_description: "Hulp bij geschillen met overheidsinstanties en bestuurlijke procedures.",
    obligations_law: "Verbintenissenrecht",
    obligations_law_description: "Contractrecht, aansprakelijkheid en andere verbintenissen tussen partijen.",
    contact_title: "Contact",
    contact_heading: "Neem contact op",
    email: "E-mail",
    phone: "Telefoon",
    location: "Locatie",
    location_value: "Zaandam, Noord-Holland",
    send_message: "Stuur een bericht",
    name_required: "Naam *",
    name_placeholder: "Uw naam",
    email_required: "E-mail *",
    email_placeholder: "uw.email@voorbeeld.nl",
    phone_optional: "Telefoon",
    phone_placeholder_optional: "06-12345678 (optioneel)",
    subject_required: "Onderwerp *",
    select_subject: "Selecteer een onderwerp",
    general_question: "Algemene vraag",
    legal_advice: "Juridisch advies",
    appointment_option: "Afspraak maken",
    request_quote: "Offerte aanvragen",
    complaint: "Klacht",
    other: "Overig",
    message_required: "Bericht *",
    message_placeholder: "Uw bericht...",
    privacy_prefix: "Ik ga akkoord met de",
    privacy_link: "privacyverklaring",
    privacy_suffix: "en geef toestemming voor het verwerken van mijn gegevens. *",
    send_message_button: "Verstuur bericht",
    contact_success: "Bedankt! Uw bericht is verzonden. We nemen binnen 24 uur contact met u op.",
    appointment_title: "Afspraak inplannen",
    close_modal: "Sluiten",
    first_name_required: "Voornaam *",
    first_name_placeholder: "Uw voornaam",
    last_name_required: "Achternaam *",
    last_name_placeholder: "Uw achternaam",
    phone_required: "Telefoon *",
    phone_placeholder: "06-12345678",
    legal_area_required: "Rechtsgebied *",
    select_legal_area: "Selecteer een rechtsgebied",
    desired_date: "Gewenste datum *",
    desired_time: "Gewenste tijd *",
    select_time: "Selecteer een tijd",
    meeting_type: "Type afspraak *",
    office_visit: "Kantoorbezoek",
    office_visit_description: "Persoonlijk gesprek op kantoor",
    video_call: "Videobellen",
    video_call_description: "Online gesprek via video",
    question_description: "Korte omschrijving van uw vraag *",
    question_placeholder: "Beschrijf kort waar u hulp bij nodig heeft...",
    cancel: "Annuleren",
    request_appointment: "Afspraak aanvragen",
    footer_tagline: "Eerlijk juridisch advies. Zonder drempels.",
    footer_copyright: "© 2025 Zaans Recht. Alle rechten voorbehouden.",
    terms: "Algemene Voorwaarden",
    captcha_required: "Bevestig a.u.b. dat u geen robot bent.",
    sending: "Bezig met verzenden...",
    send_error: "Er ging iets mis bij het verzenden. Probeer het later opnieuw.",
    appointment_success: "Afspraak succesvol aangevraagd!",
    mobile_menu_message: "Gebruik de navigatielinks bovenaan op een groter scherm.",
  },
  en: {
    page_title: "Zaans Recht - Fair legal advice",
    language_label: "Language",
    close_notification: "Close notification",
    nav_about: "About us",
    nav_services: "Services",
    nav_contact: "Contact",
    welcome: "Welcome to Zaans Recht!",
    hero_intro: "We provide free legal advice and clarity about your rights.",
    hero_explanation: "This helps you understand your legal situation clearly and easily.",
    hero_action: "At Zaans Recht, your rights come first. Do you have questions or need support? Make an appointment!",
    make_appointment: "Make an appointment",
    about_title: "About us",
    about_description_1: "Zaans Recht offers free legal advice to anyone with questions about their rights. Our goal is to clarify people's legal situations and provide understandable advice, enabling them to make informed decisions.",
    about_description_2: "We understand that legal matters can be complicated. We are ready to guide you across various areas of law. Alongside free advice, we can prepare legal documents such as notices of objection and complaint letters. Any associated costs will be discussed with you in advance.",
    walk_in: "Every Thursday at 4:00 PM, you can visit our walk-in consultation without an appointment at Bibliotheek Zaandam (Westzijde 170 A, 1506 EK Zaandam).",
    services_title: "Services",
    corporate_law: "Corporate law",
    corporate_law_description: "Legal support for entrepreneurs, from contracts to disputes.",
    family_law: "Family law",
    family_law_description: "Guidance with divorce, maintenance and contact arrangements.",
    employment_law: "Employment law",
    employment_law_description: "Advice on workplace disputes, dismissal and employment contracts.",
    administrative_law: "Administrative law",
    administrative_law_description: "Help with disputes involving public authorities and administrative procedures.",
    obligations_law: "Law of obligations",
    obligations_law_description: "Contract law, liability and other obligations between parties.",
    contact_title: "Contact",
    contact_heading: "Get in touch",
    email: "Email",
    phone: "Phone",
    location: "Location",
    location_value: "Zaandam, North Holland",
    send_message: "Send a message",
    name_required: "Name *",
    name_placeholder: "Your name",
    email_required: "Email *",
    email_placeholder: "your.email@example.com",
    phone_optional: "Phone",
    phone_placeholder_optional: "06-12345678 (optional)",
    subject_required: "Subject *",
    select_subject: "Select a subject",
    general_question: "General question",
    legal_advice: "Legal advice",
    appointment_option: "Make an appointment",
    request_quote: "Request a quote",
    complaint: "Complaint",
    other: "Other",
    message_required: "Message *",
    message_placeholder: "Your message...",
    privacy_prefix: "I agree to the",
    privacy_link: "privacy statement",
    privacy_suffix: "and consent to the processing of my data. *",
    send_message_button: "Send message",
    contact_success: "Thank you! Your message has been sent. We will contact you within 24 hours.",
    appointment_title: "Schedule an appointment",
    close_modal: "Close",
    first_name_required: "First name *",
    first_name_placeholder: "Your first name",
    last_name_required: "Last name *",
    last_name_placeholder: "Your last name",
    phone_required: "Phone *",
    phone_placeholder: "06-12345678",
    legal_area_required: "Area of law *",
    select_legal_area: "Select an area of law",
    desired_date: "Preferred date *",
    desired_time: "Preferred time *",
    select_time: "Select a time",
    meeting_type: "Appointment type *",
    office_visit: "Office visit",
    office_visit_description: "In-person meeting at the office",
    video_call: "Video call",
    video_call_description: "Online meeting by video",
    question_description: "Brief description of your question *",
    question_placeholder: "Briefly describe what you need help with...",
    cancel: "Cancel",
    request_appointment: "Request appointment",
    footer_tagline: "Fair, accessible legal advice.",
    footer_copyright: "© 2025 Zaans Recht. All rights reserved.",
    terms: "Terms and Conditions",
    captcha_required: "Please confirm that you are not a robot.",
    sending: "Sending...",
    send_error: "Something went wrong while sending. Please try again later.",
    appointment_success: "Your appointment request was sent successfully!",
    mobile_menu_message: "Use the navigation links at the top on a larger screen.",
  },
  ar: {
    page_title: "حقوق زاندام - استشارة قانونية عادلة",
    language_label: "اللغة",
    close_notification: "إغلاق الإشعار",
    nav_about: "من نحن",
    nav_services: "الخدمات",
    nav_contact: "اتصل بنا",
    welcome: "مرحباً بكم في حقوق زاندام!",
    hero_intro: "نقدم استشارات قانونية مجانية ونوضح لكم حقوقكم.",
    hero_explanation: "وبذلك نساعدكم على فهم وضعكم القانوني بسهولة ووضوح.",
    hero_action: "في حقوق زاندام، حقوقكم هي أولويتنا. هل لديكم أسئلة أو تحتاجون إلى دعم؟ احجزوا موعداً!",
    make_appointment: "احجز موعداً",
    about_title: "من نحن",
    about_description_1: "نقدم في حقوق زاندام استشارات قانونية مجانية لكل من لديه أسئلة حول حقوقه. هدفنا هو مساعدة الناس على فهم أوضاعهم القانونية وتقديم نصائح واضحة تمكّنهم من اتخاذ قرارات مدروسة.",
    about_description_2: "ندرك أن المسائل القانونية قد تكون معقدة، ولذلك نرشدكم في مختلف مجالات القانون. وإلى جانب الاستشارة المجانية، يمكننا إعداد مستندات قانونية مثل الاعتراضات ورسائل الشكاوى. وسنناقش معكم أي تكاليف مسبقاً.",
    walk_in: "يمكنكم زيارتنا كل يوم خميس الساعة 16:00 دون موعد خلال ساعات الاستشارة المفتوحة في مكتبة زاندام (Westzijde 170 A, 1506 EK Zaandam).",
    services_title: "الخدمات",
    corporate_law: "قانون الشركات",
    corporate_law_description: "دعم قانوني لرواد الأعمال، من العقود إلى النزاعات.",
    family_law: "قانون الأسرة",
    family_law_description: "إرشاد في الطلاق والنفقة وترتيبات التواصل.",
    employment_law: "قانون العمل",
    employment_law_description: "استشارات بشأن نزاعات العمل والفصل وعقود العمل.",
    administrative_law: "القانون الإداري",
    administrative_law_description: "المساعدة في النزاعات مع الجهات الحكومية والإجراءات الإدارية.",
    obligations_law: "قانون الالتزامات",
    obligations_law_description: "قانون العقود والمسؤولية والالتزامات الأخرى بين الأطراف.",
    contact_title: "اتصل بنا",
    contact_heading: "تواصل معنا",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    location: "الموقع",
    location_value: "زاندام، شمال هولندا",
    send_message: "أرسل رسالة",
    name_required: "الاسم *",
    name_placeholder: "اسمك",
    email_required: "البريد الإلكتروني *",
    email_placeholder: "your.email@example.com",
    phone_optional: "الهاتف",
    phone_placeholder_optional: "06-12345678 (اختياري)",
    subject_required: "الموضوع *",
    select_subject: "اختر موضوعاً",
    general_question: "سؤال عام",
    legal_advice: "استشارة قانونية",
    appointment_option: "حجز موعد",
    request_quote: "طلب عرض سعر",
    complaint: "شكوى",
    other: "أخرى",
    message_required: "الرسالة *",
    message_placeholder: "اكتب رسالتك...",
    privacy_prefix: "أوافق على",
    privacy_link: "بيان الخصوصية",
    privacy_suffix: "وأوافق على معالجة بياناتي. *",
    send_message_button: "إرسال الرسالة",
    contact_success: "شكراً لكم! تم إرسال رسالتكم وسنتواصل معكم خلال 24 ساعة.",
    appointment_title: "حجز موعد",
    close_modal: "إغلاق",
    first_name_required: "الاسم الأول *",
    first_name_placeholder: "اسمك الأول",
    last_name_required: "اسم العائلة *",
    last_name_placeholder: "اسم العائلة",
    phone_required: "الهاتف *",
    phone_placeholder: "06-12345678",
    legal_area_required: "المجال القانوني *",
    select_legal_area: "اختر مجالاً قانونياً",
    desired_date: "التاريخ المفضل *",
    desired_time: "الوقت المفضل *",
    select_time: "اختر وقتاً",
    meeting_type: "نوع الموعد *",
    office_visit: "زيارة المكتب",
    office_visit_description: "لقاء شخصي في المكتب",
    video_call: "مكالمة فيديو",
    video_call_description: "لقاء عبر الفيديو",
    question_description: "وصف مختصر لسؤالكم *",
    question_placeholder: "اشرحوا باختصار ما تحتاجون إلى المساعدة فيه...",
    cancel: "إلغاء",
    request_appointment: "طلب موعد",
    footer_tagline: "استشارة قانونية عادلة ومتاحة للجميع.",
    footer_copyright: "© 2025 حقوق زاندام. جميع الحقوق محفوظة.",
    terms: "الشروط والأحكام",
    captcha_required: "يرجى تأكيد أنكم لستم روبوتاً.",
    sending: "جارٍ الإرسال...",
    send_error: "حدث خطأ أثناء الإرسال. يرجى المحاولة مرة أخرى لاحقاً.",
    appointment_success: "تم إرسال طلب الموعد بنجاح!",
    mobile_menu_message: "استخدموا روابط التنقل في الأعلى على شاشة أكبر.",
  },
};

let currentLanguage = "nl";

function translate(key) {
  return translations[currentLanguage]?.[key] ?? translations.nl[key] ?? key;
}

function setLang(lang) {
  if (!translations[lang]) {
    lang = "nl";
  }
  currentLanguage = lang;
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  document.title = translate("page_title");

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    element.textContent = translate(element.dataset.i18n);
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
    element.placeholder = translate(element.dataset.i18nPlaceholder);
  });
  document.querySelectorAll("[data-i18n-aria-label]").forEach((element) => {
    element.setAttribute("aria-label", translate(element.dataset.i18nAriaLabel));
  });

  localStorage.setItem("zaansrecht-language", lang);
  document.dispatchEvent(new CustomEvent("languagechange", { detail: { lang } }));
}

window.zaansrechtI18n = { setLang, t: translate };

document.addEventListener("DOMContentLoaded", () => {
  const selector = document.getElementById("languageSelect");
  const savedLanguage = localStorage.getItem("zaansrecht-language");
  const initialLanguage = translations[savedLanguage] ? savedLanguage : "nl";

  if (selector) {
    selector.value = initialLanguage;
    selector.addEventListener("change", (event) => setLang(event.target.value));
  }
  setLang(initialLanguage);
});
