# Generated by Django 4.2.23 on 2025-08-11 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpanglishPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=500)),
                ('english_translation', models.CharField(max_length=500)),
                ('spanish_translation', models.CharField(max_length=500)),
                ('context', models.TextField(blank=True, help_text='When to use this phrase')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='spanglish.category')),
            ],
            options={
                'verbose_name': 'Spanglish Phrase',
                'verbose_name_plural': 'Spanglish Phrases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpanglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=200)),
                ('spanish_word', models.CharField(max_length=200)),
                ('spanglish_word', models.CharField(max_length=200)),
                ('definition', models.TextField(blank=True)),
                ('example_sentence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spanglish Word',
                'verbose_name_plural': 'Spanglish Words',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('novice', 'Novice'), ('apprentice', 'Apprentice'), ('expert', 'Expert'), ('master', 'Master')], default='novice', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phrases_learned', models.ManyToManyField(blank=True, to='spanglish.spanglishphrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('words_learned', models.ManyToManyField(blank=True, to='spanglish.spanglishword')),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
                'unique_together': {('user',)},
            },
        ),
    ]
